drones:
- id: 1
  velocity: 3.69
- id: 2
  velocity: 4.57
- id: 3
  velocity: 3.54
- id: 4
  velocity: 3.12
- id: 5
  velocity: 4.44
- id: 6
  velocity: 4.83
- id: 7
  velocity: 4.4
- id: 8
  velocity: 3.05
- id: 9
  velocity: 3.69
- id: 10
  velocity: 3.48
- id: 11
  velocity: 5.0
- id: 12
  velocity: 3.07
- id: 13
  velocity: 4.49
- id: 14
  velocity: 3.88
- id: 15
  velocity: 4.66
package_stations:
- id: 1
  position:
  - 77
  - 87
  lockers: 15
- id: 2
  position:
  - 86
  - 61
  lockers: 14
- id: 3
  position:
  - 50
  - 38
  lockers: 18
- id: 4
  position:
  - 93
  - 13
  lockers: 9
- id: 5
  position:
  - 74
  - 95
  lockers: 10
- id: 6
  position:
  - 54
  - 79
  lockers: 5
- id: 7
  position:
  - 91
  - 99
  lockers: 18
- id: 8
  position:
  - 10
  - 24
  lockers: 16
- id: 9
  position:
  - 16
  - 42
  lockers: 15
- id: 10
  position:
  - 76
  - 67
  lockers: 16
- id: 11
  position:
  - 24
  - 85
  lockers: 18
- id: 12
  position:
  - 98
  - 20
  lockers: 17
- id: 13
  position:
  - 78
  - 70
  lockers: 16
- id: 14
  position:
  - 98
  - 74
  lockers: 16
- id: 15
  position:
  - 29
  - 5
  lockers: 11
- id: 16
  position:
  - 53
  - 74
  lockers: 19
- id: 17
  position:
  - 19
  - 28
  lockers: 16
- id: 18
  position:
  - 7
  - 66
  lockers: 20
- id: 19
  position:
  - 50
  - 12
  lockers: 16
- id: 20
  position:
  - 0
  - 76
  lockers: 7
