drones:
- id: 1
  velocity: 1.3
- id: 2
  velocity: 1.68
- id: 3
  velocity: 1.7
- id: 4
  velocity: 1.47
- id: 5
  velocity: 1.06
package_stations:
- id: 1
  position:
  - 12
  - 86
  lockers: 12
- id: 2
  position:
  - 85
  - 2
  lockers: 11
- id: 3
  position:
  - 26
  - 91
  lockers: 11
